### ISSUE TITLE
Instance Hardness -  emit warning if IH_rate is large than the maximum value

### ISSUE THREAD

**Issue by luizgh** [Menelau/DESlib#114]
@Menelau, Victor raised an interesting comment about how IH is calculated, and I think it may be interesting to warn the user in some scenarios.

In summary, the way that IH is calculated it has a maximum value lower than 1 (since we are using the mode of the predictions of the safe neighborhood instead of the true class). In particular, when the samples in the safe neighborhood are equally distributed across all "n_classes", we have the highest possible IH:

(safe_k - ceil(safe_k / n_classes)) / safe_k

For example, for a 2-class classification problem, and safe_k = 7, we have:
(7 - 4)/ 7  = 0.428..

Users may expect that this value should go from 0 to 1 (which is the case for IH when calculated using the true class). One thing we can do is to keep the computation as is, but emit a warning if the user asks for IH, and use a IH_rate higher than the maximum (for a specific n_classes x safe_k combination).

**Comment by Menelau** [comment]
That is a very good point, we need to handle this case, and also have in the documentation of the IH function its range.

Btw, that would be a very nice issue to work as first contribution if Victor wants to start contributing to the library.

**Comment by victorlorena** [comment]
@Menelau Why the IH_rate value cannot be greater than 0.5?

For example, for a 3-class classification problem, and safe_k = 9, we can have a neighborhood with four instances from class 0, three instances from class 1 and two instances from class 2. In this case, we have IH = (9 - 4)/9 = 0.555...

**Comment by Menelau** [comment]
@victorlorena You are right, it is possible to be greater than 0.5 (0.5 would be the limit for one specific scenario). The highest value changes according to the number of classes & k value used. 
So we need to take into account these two values.

This value is also specific to this specific measure of IH.
