### ISSUE TITLE
installation works at ubuntu but failed at windows 10

### ISSUE THREAD

**Issue by alzami1986** [Menelau/DESlib#40]
hello, I am trying to install through pip install git+https://github.com/Menelau/DESlib but it failed.
the error traceback as follows:

(python35) C:\Users\alzami>pip install git+https://github.com/Menelau/DESlib.git
Collecting git+https://github.com/Menelau/DESlib.git
Cloning https://github.com/Menelau/DESlib.git to c:\users\alzami\appdata\local\temp\pip-bduwwk_u-build
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "", line 1, in 
File "C:\Users\alzami\AppData\Local\Temp\pip-bduwwk_u-build\setup.py", line 10, in 
README = f.read()
File "D:\AnacondaInstallation\envs\python35\lib\encodings\cp1252.py", line 23, in decode
return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 5392: character maps to

----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\alzami\AppData\Local\Temp\pip-bduwwk_u-build\

notes: it works on ubuntu

**Comment by Menelau** [comment]
Hello,

I believe it was a problem reading a file with a different encoding. I changed the configuration of setup.py and tested the installation on Windows 10. It should work now

**Comment by alzami1986** [comment]
it works, thank you
