### ISSUE TITLE
Check estimators with instances: include on unit tests

### ISSUE THREAD

**Issue by luizgh** [Menelau/DESlib#90]
Mocks need not to have the "get_params" method to be deep copied. An alternative is to actually have a classifier during the test

**Comment by luizgh** [comment]
I did some work on this, and realized that these tests will not work on instances of the DS classes that are constructed **receiving a pool of classifiers**. The base classifiers will have been fit already for a specific number of classes, while the checks will "fit" the DS classifier with another number of classes. 

In other words, in all sklearn classifiers, the "fit" method is when the classifier learns the number of classes, whereas for DS instances that are initialized with a pool of classifiers, the number of classes is already defined on the construction of the DS class. This creates a problem since the tests on "check_estimator" use different number of classes:

  example: check_pipeline_consistency (estimator_checks.py:767) uses 2 classes, while
	   check_estimators_dtypes (estimator_checks.py:827) uses 3 classes

If we use base classifiers that outputs results for 3 classes, the first check fails; if it outputs for 2 classes, the second check fails.

Bottomline: I think we should just create tests for the DS classes, not DS instances. Although we could create tests for DS instances initialized without a pool of classifiers, the check_estimator would just apply the same tests as if testing a DS class. 
I think the only way that we could test the DS instances initialized with a pool of classifiers is if we do a major change in the library, where the base classifiers are not fit before being used to initialize a DS class, but rather everything is fit in the DS "fit" method (which I think will limit the usage of the library).

@Menelau let me know what you think. In my opinion we should just close this issue, and keep only the tests for DS classes.

**Comment by luizgh** [comment]
Here is a test that triggers this scenario:

```
from sklearn.utils.estimator_checks import check_estimator


def create_base_classifier_proba(n_classes, seed):
    def get_proba(X):
        rng = np.random.RandomState(seed)
        n_examples = len(X)
        logits = rng.rand(n_examples, n_classes)
        probs = np.exp(logits) / np.sum(np.exp(logits), axis=0)

        return probs

    def get_pred(X):
        probs = get_proba(X)
        preds = probs.argmax(axis=1)
        return preds

    classifier = MagicMock()
    classifier.predict.side_effect = get_pred
    classifier.predict_proba.side_effect = get_proba
    del classifier.get_params

    return classifier


def test_check_estimator():
    clf1 = create_base_classifier_proba(n_classes=3, seed=1)
    clf2 = create_base_classifier_proba(n_classes=3, seed=2)
    clf3 = create_base_classifier_proba(n_classes=3, seed=3)

    pool_classifiers = [clf1, clf2, clf3]

    target = DESKNN(pool_classifiers, k=7, pct_accuracy=1, pct_diversity=1)

    check_estimator(target)
```

**Comment by Menelau** [comment]
@luizgh I agree, we should close this issue. Since it will just apply the same test there is no need to create more or change the whole way the library works just for that. In my opinion, having the pool of classifiers fitted before passing it to the DS methods is better, because usually, we want to evaluate the same pool on several DS methods (as well as static combination). So always fitting inside the DS "fit" method makes no sense.

**Comment by luizgh** [comment]
Ok, thanks for confirming. I will close the issue
